</div><!-- sub-content -->

</div><!-- /content -->

<div id="footer">
<h3 class="hide">Copyright notice and other geekery</h3>
<ul>
	<li>Copyright &copy; Irssi Project </li>

</ul>
</div><!-- /footer -->

</div><!-- /wrapper -->
</div><!-- /wrap -->

<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-1191860-1";
urchinTracker();
</script>

</body>

</html>

