

	</div><!-- /main-content -->

	<div id="sub-content">

<!-- TOODODODODODODO

<li id="sub-menuactive"><a id="sub-menucurrent"

-->	
		
		<ul id="sub-menu">
			<li><a href="/documentation/startup" title="Startup HOWTO">Startup HOWTO</a></li>

			<li><a href="/documentation/faq" title="FAQ">FAQ</a></li>
			<li><a href="/documentation/bugs" title="Writing good bug reports">Writing good bug reports</a></li>
			<li><a href="/documentation/design" title="Design">Design</a></li>
			<li><a href="/documentation/manual" title="Manual">Manual</a></li>
			<li><a href="/documentation/tips" title="Tips &#038; Tricks">Tips &amp; Tricks</a></li>
			<li><a href="/documentation/proxy" title="Irssi Proxy">Irssi Proxy</a></li>

			<li><a href="/documentation/formats" title="Color Formats">Color Formats</a></li>
			<li><a href="/documentation/variables" title="Special Variables">Special Variables</a></li>
			<li><a href="/documentation/scripting" title="Perl Scripting Reference">Perl Scripting Reference</a></li>
			<li><a href="/documentation/signals" title="Signals">Signals</a></li>
		</ul>

		<div id="download">
		  <p class="intro">Download Irssi</p>
		  <p class="version"><em><a href="#" class="release">version 0.8.1</a></em></p>
		</div>
	
	
