<?php

## General information.
#
# File name:   module.php
# Last update: Thu Dec  8 16:03:00 2005
#
##

## Bugreports and License disclaimer.
#
# For bugreports and other improvements contact The Irssi Project <staff@irssi.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this script; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
##

##
# Irssi Documentation module.
#
#    This module will display the Irssi docs.
##

Class IrssiDocumentation {

    ##
    # Variables to store instances of this module and other core classes.
    ##

    var $core;

    ##
    # Irssi Documentation constructor.
    ##

    function IrssiDocumentation (&$core) {
        $this->core =& $core;
    }

    function load () {

        ##
        # Some documentation is imported from the Irssi SVN repository and is location into the
        # temporary documentation directory which is generated by a Perl script.
        ##

        #$import = @parse_ini_file(BASEDIR . "modules/" . $this->core->CurrentUserModule . "/convert.ini");

        ##
        # We don't want the header and footers for the settings page because it's a standalone page.
        # This is still placed incorrectly here. Make an ob_* when including the file, have the file set
        # CUSTOM_BODY itself and then include header / print ob_*content* / include footer.
        # One possible place where this causes problems: settings page does not exist.
        ##

        if (($_REQUEST[action] == 'settings') && (file_exists(BASEDIR . "tmp/" . $this->core->CurrentUserModule . "/settings.page"))) {
            $this->core->DefaultHeader = 0;
        }

        require_once(BASEDIR . 'html/header.inc');

        ##
        # Display the correct requested pages.
        ##

        if (($_REQUEST[action] == 'settings') && (file_exists(BASEDIR . "tmp/" . $this->core->CurrentUserModule . "/settings.page"))) {
            require_once(BASEDIR . "tmp/" . $this->core->CurrentUserModule . "/settings.page");
        } elseif (file_exists(((isset($_REQUEST['action'])) ? BASEDIR . "modules/" . $this->core->CurrentUserModule . "/pages/${_REQUEST['action']}.page" : BASEDIR . "modules/" . $this->core->CurrentUserModule . "/pages/documentation.page"))) {
            require_once((isset($_REQUEST['action'])) ? BASEDIR . "modules/" . $this->core->CurrentUserModule . "/pages/${_REQUEST['action']}.page" : BASEDIR . "modules/" . $this->core->CurrentUserModule .  '/pages/documentation.page');
	} else {
            require_once(BASEDIR . "html/404.inc");
        }

        require_once(BASEDIR . 'html/footer.inc');
    }
}
?>
